list_of_entities_found_by_gpt = [
    "Acne", 
    "skin condition", 
    "hair follicles", 
    "oil", 
    "dead skin cells", 
    "whiteheads", 
    "blackheads", 
    "pimples", 
    "bumps", 
    "papules", 
    "pustules", 
    "nodules", 
    "cystic lesions", 
    "face", 
    "forehead", 
    "chest", 
    "upper back", 
    "shoulders", 
    "doctor", 
    "primary care doctor", 
    "stronger medications", 
    "medical treatment", 
    "dermatologist", 
    "pediatric dermatologist", 
    "FDA", 
    "nonprescription acne lotions", 
    "cleansers", 
    "skin products", 
    "serious reaction", 
    "redness", 
    "irritation", 
    "itchiness", 
    "emergency medical help", 
    "faintness", 
    "difficulty breathing", 
    "swelling", 
    "Food and Drug Administration", 
    "excess oil", 
    "sebum", 
    "hair follicles", 
    "dead skin cells", 
    "bacteria", 
    "inflammation", 
    "follicle wall", 
    "whitehead", 
    "blackhead", 
    "pimple", 
    "sweat glands", 
    "androgens", 
    "puberty", 
    "corticosteroids", 
    "testosterone", 
    "lithium", 
    "diet", 
    "carbohydrate-rich foods", 
    "stress", 
    "acne myths", 
    "chocolate", 
    "greasy foods", 
    "hygiene", 
    "scrubbing", 
    "soaps", 
    "chemicals", 
    "cosmetics", 
    "complications", 
    "darker skin types", 
    "lighter skin", 
    "acne scars", 
    "keloids", 
    "skin changes", 
    "hyperpigmented", 
    "hypopigmented", 
    "risk factors", 
    "teenagers", 
    "puberty", 
    "pregnancy", 
    "genetics", 
    "parents", 
    "oily substances", 
    "friction", 
    "pressure",
    "Acromegaly",
    "medical condition",
    "growth hormone",
    "body",
    "bones",
    "tissues",
    "irregular ways",
    "treatments",
    "surgery",
    "medication",
    "radiation therapy",
    "pituitary gland",
    "pea-sized endocrine gland",
    "base",
    "brain",
    "hypothalamus",
    "hormones",
    "GH",
    "human growth hormone",
    "somatotropin",
    "children",
    "height",
    "bones",
    "cartilage",
    "organ structure",
    "metabolism",
    "blood glucose",
    "diabetes",
    "blood pressure",
    "heart disease",
    "gigantism",
    "adults",
    "children",
    "puberty",
    "frequency",
    "body",
    "appearance",
    "hands",
    "feet",
    "ears",
    "lips",
    "nose",
    "jaw",
    "forehead",
    "liver",
    "hormone",
    "insulin-like growth factor 1",
    "IGF-1",
    "Type 2 diabetes",
    "high blood pressure",
    "symptoms",
    "causes",
    "tumor",
    "pituitary adenoma",
    "location",
    "adenoma",
    "pituitary tissue",
    "hormones",
    "headaches",
    "vision problems",
    "size",
    "shape",
    "hands",
    "feet",
    "face",
    "jaw",
    "forehead",
    "voice",
    "sweating",
    "oily skin",
    "skin tags",
    "numbness",
    "sleep apnea",
    "Carpal tunnel syndrome",
    "spinal cord issues",
    "diagnosis",
    "tests",
    "endocrinologist",
    "history",
    "evaluation",
    "blood tests",
    "imaging tests",
    "echocardiogram",
    "heart issues",
    "sleep study tests",
    "colonoscopy",
    "colon",
    "X-rays",
    "DEXA scan",
    "treatment",
    "severity",
    "therapies",
    "improvement",
    "self-image",
    "quality of life",
    "support groups",
    "complications",
    "life expectancy",
    "health conditions",
    "years",
    "insulin-like growth factor 1",
    "life expectancy",
    "healthcare provider",
    "symptoms",
    "tests",
    "Acute Lymphoblastic Leukemia",
    "ALL",
    "cancer",
    "blood",
    "bone marrow",
    "white blood cells",
    "infection",
    "children",
    "adults",
    "chemotherapy",
    "lymphocytes",
    "rare blood cancer",
    "genetic mutations",
    "B-cell ALL",
    "T-cell ALL",
    "natural killer ALL",
    "symptoms",
    "anemia",
    "bleeding",
    "bruising",
    "cough",
    "dizziness",
    "fatigue",
    "fever",
    "infections",
    "joint pain",
    "loss of appetite",
    "night sweats",
    "petechiae",
    "shortness of breath",
    "skin color changes",
    "swollen lymph nodes",
    "weight loss",
    "weakness",
    "risk factors",
    "sex",
    "race",
    "radiation exposure",
    "viruses",
    "genetic conditions",
    "complications",
    "brain and spine",
    "balance problems",
    "vision problems",
    "muscle weakness",
    "headaches",
    "nausea",
    "vomiting",
    "hepatomegaly",
    "splenomegaly",
    "SVC syndrome",
    "diagnosis",
    "tests",
    "complete blood count",
    "bone marrow biopsy",
    "lymph node biopsy",
    "lumbar puncture",
    "MRI",
    "CT scan",
    "PET scan",
    "flow cytometry",
    "cytogenetic tests",
    "molecular assays",
    "treatments",
    "targeted therapy",
    "immunotherapy",
    "stem cells transplantation",
    "chemotherapy phases",
    "remission induction therapy",
    "central nervous system-directed therapy",
    "consolidation therapy",
    "continuation or maintenance therapy",
    "radiation therapy",
    "allogeneic stem cell transplantation",
    "prognosis",
    "survival rate",
    "chronic disease",
    "support groups",
    "cancer survivorship programs",
    "follow-up care",
    "stress management",
    "exercise",
    "clinical trials",
]

acromegaly_entities = [
    "Acromegaly",
    "medical condition",
    "growth hormone",
    "body",
    "bones",
    "tissues",
    "irregular ways",
    "treatments",
    "surgery",
    "medication",
    "radiation therapy",
    "pituitary gland",
    "pea-sized endocrine gland",
    "base",
    "brain",
    "hypothalamus",
    "hormones",
    "GH",
    "human growth hormone",
    "somatotropin",
    "children",
    "height",
    "bones",
    "cartilage",
    "organ structure",
    "metabolism",
    "blood glucose",
    "diabetes",
    "blood pressure",
    "heart disease",
    "gigantism",
    "adults",
    "children",
    "puberty",
    "frequency",
    "body",
    "appearance",
    "hands",
    "feet",
    "ears",
    "lips",
    "nose",
    "jaw",
    "forehead",
    "liver",
    "hormone",
    "insulin-like growth factor 1",
    "IGF-1",
    "Type 2 diabetes",
    "high blood pressure",
    "symptoms",
    "causes",
    "tumor",
    "pituitary adenoma",
    "location",
    "adenoma",
    "pituitary tissue",
    "hormones",
    "headaches",
    "vision problems",
    "size",
    "shape",
    "hands",
    "feet",
    "face",
    "jaw",
    "forehead",
    "voice",
    "sweating",
    "oily skin",
    "skin tags",
    "numbness",
    "sleep apnea",
    "Carpal tunnel syndrome",
    "spinal cord issues",
    "diagnosis",
    "tests",
    "endocrinologist",
    "history",
    "evaluation",
    "blood tests",
    "imaging tests",
    "echocardiogram",
    "heart issues",
    "sleep study tests",
    "colonoscopy",
    "colon",
    "X-rays",
    "DEXA scan",
    "treatment",
    "severity",
    "therapies",
    "improvement",
    "self-image",
    "quality of life",
    "support groups",
    "complications",
    "life expectancy",
    "health conditions",
    "years",
    "insulin-like growth factor 1",
    "life expectancy",
    "healthcare provider",
    "symptoms",
    "tests"
]

all_entities = [
    "Acute Lymphoblastic Leukemia",
    "ALL",
    "cancer",
    "blood",
    "bone marrow",
    "white blood cells",
    "infection",
    "children",
    "adults",
    "chemotherapy",
    "lymphocytes",
    "rare blood cancer",
    "genetic mutations",
    "B-cell ALL",
    "T-cell ALL",
    "natural killer ALL",
    "symptoms",
    "anemia",
    "bleeding",
    "bruising",
    "cough",
    "dizziness",
    "fatigue",
    "fever",
    "infections",
    "joint pain",
    "loss of appetite",
    "night sweats",
    "petechiae",
    "shortness of breath",
    "skin color changes",
    "swollen lymph nodes",
    "weight loss",
    "weakness",
    "risk factors",
    "sex",
    "race",
    "radiation exposure",
    "viruses",
    "genetic conditions",
    "complications",
    "brain and spine",
    "balance problems",
    "vision problems",
    "muscle weakness",
    "headaches",
    "nausea",
    "vomiting",
    "hepatomegaly",
    "splenomegaly",
    "SVC syndrome",
    "diagnosis",
    "tests",
    "complete blood count",
    "bone marrow biopsy",
    "lymph node biopsy",
    "lumbar puncture",
    "MRI",
    "CT scan",
    "PET scan",
    "flow cytometry",
    "cytogenetic tests",
    "molecular assays",
    "treatments",
    "targeted therapy",
    "immunotherapy",
    "stem cells transplantation",
    "chemotherapy phases",
    "remission induction therapy",
    "central nervous system-directed therapy",
    "consolidation therapy",
    "continuation or maintenance therapy",
    "radiation therapy",
    "allogeneic stem cell transplantation",
    "prognosis",
    "survival rate",
    "chronic disease",
    "support groups",
    "cancer survivorship programs",
    "follow-up care",
    "stress management",
    "exercise",
    "clinical trials",
]

anemia_entities = [
    "Anemia",
    "red blood cells",
    "hemoglobin",
    "oxygen",
    "tissues",
    "protein",
    "lungs",
    "organs",
    "tiredness",
    "weakness",
    "shortness of breath",
    "forms of anemia",
    "short term",
    "long term",
    "severity",
    "warning sign",
    "illness",
    "treatments",
    "supplements",
    "medical procedures",
    "healthy diet",
    "Products & Services",
    "Aplastic anemia",
    "Iron deficiency anemia",
    "Sickle cell anemia",
    "Thalassemia",
    "Vitamin deficiency anemia",
    "Symptoms",
    "Pale skin",
    "yellowish skin",
    "Irregular heartbeat",
    "Dizziness",
    "Lightheadedness",
    "Chest pain",
    "Cold hands",
    "Cold feet",
    "Headaches",
    "doctor's appointment",
    "hemoglobin levels",
    "Causes",
    "blood",
    "bleeding",
    "red blood cells",
    "iron",
    "vitamin B-12",
    "folate",
    "nutrients",
    "bone marrow",
    "iron deficiency anemia",
    "Pregnancy",
    "vitamin deficiency anemia",
    "inflammation",
    "Aplastic anemia",
    "blood diseases",
    "bone marrow disease",
    "Hemolytic anemias",
    "Sickle cell anemia",
    "Risk factors",
    "diet",
    "vitamins",
    "minerals",
    "small intestine",
    "chronic conditions",
    "ulcer",
    "family history",
    "infections",
    "blood diseases",
    "autoimmune conditions",
    "alcohol consumption",
    "toxic chemicals",
    "medicines",
    "age",
    "Complications",
    "severe tiredness",
    "pregnancy complications",
    "heart problems",
    "arrhythmia",
    "enlarged heart",
    "heart failure",
    "death",
    "Prevention",
    "healthy diet",
    "Iron",
    "Folate",
    "Vitamin B-12",
    "Vitamin C",
    "multivitamin",
]

ashtma_entities = [
    "Asthma",
    "airways",
    "mucus",
    "breathing",
    "coughing",
    "wheezing",
    "shortness of breath",
    "symptoms",
    "severity",
    "treatment",
    "doctor",
    "signs",
    "minor nuisance",
    "major problem",
    "life-threatening asthma attack",
    "control",
    "environmental factors",
    "genetic factors",
    "irritants",
    "allergies",
    "pollen",
    "dust mites",
    "mold spores",
    "pet dander",
    "cockroach waste",
    "respiratory infections",
    "physical activity",
    "cold air",
    "air pollutants",
    "smoke",
    "medications",
    "beta blockers",
    "aspirin",
    "nonsteroidal anti-inflammatory drugs",
    "stress",
    "sulfites",
    "preservatives",
    "Gastroesophageal reflux disease",
    "blood relatives",
    "allergic conditions",
    "atopic dermatitis",
    "hay fever",
    "overweight",
    "smoker",
    "secondhand smoke",
    "exhaust fumes",
    "pollution",
    "occupational triggers",
    "complications",
    "sleep",
    "work",
    "permanent narrowing",
    "bronchial tubes",
    "emergency room visits",
    "hospitalizations",
    "side effects",
    "prevention",
    "asthma action plan",
    "vaccinations",
    "influenza",
    "pneumonia",
    "triggers",
    "monitoring",
    "breathing",
    "peak airflow",
    "peak flow meter",
    "attacks",
    "medication",
    "quick-relief inhaler",
    "albuterol",
]

covid_entities = [
    "COVID-19",
    "coronavirus disease 2019",
    "virus",
    "severe acute respiratory syndrome coronavirus 2",
    "SARS-CoV-2",
    "pandemic",
    "illness",
    "symptoms",
    "vaccine",
    "hospital care",
    "death",
    "air flow",
    "physical distancing",
    "mask",
    "hygiene",
    "medicine",
    "long-term effects",
    "dry cough",
    "shortness of breath",
    "loss of taste",
    "loss of smell",
    "fatigue",
    "digestive symptoms",
    "upset stomach",
    "vomiting",
    "diarrhea",
    "pain",
    "headaches",
    "body aches",
    "muscle aches",
    "fever",
    "chills",
    "cold-like symptoms",
    "congestion",
    "runny nose",
    "sore throat",
    "asymptomatic",
    "presymptomatic",
    "hospitalization",
    "respiratory system",
    "multisystem inflammatory syndrome",
    "MIS-C",
    "MIS-A",
    "healthcare professional",
    "emergency help",
    "breathing problems",
    "confusion",
    "chest pain",
    "risk factors",
    "infection",
    "transmission",
    "droplets",
    "mutations",
    "pets",
    "surface transmission",
    "COVID-19 vaccine",
    "immune defense",
    "inflammation",
    "blood clots",
    "kidney injury",
    "post-COVID-19 syndrome",
    "long COVID",
    "PASC",
    "vaccination",
    "Pfizer-BioNTech COVID-19 vaccine",
    "Moderna COVID-19 vaccine",
    "Novavax COVID-19 vaccine",
    "immune system",
    "body mass index",
    "risk assessment",
    "serious illness",
    "complications",
    "acute respiratory distress syndrome",
    "shock",
    "inflammatory response",
    "travel",
    "masking",
]

