version: '3.7'

services:
    minio:
        hostname: minio
        image: 'minio/minio:latest'
        container_name: minio
        ports:
        - "9001:9001"
        - "9000:9000"
        command: [ "server", "/data", "--console-address", ":9001" ]
        volumes:
        - minio-data:/data
        ############################- ./tmp/.minio:/root/.minio  #keys
        environment:
            MINIO_ROOT_USER: redda
            MINIO_ROOT_PASSWORD: SnowinRio
            MINIO_ACCESS_KEY: redda
            MINIO_SECRET_KEY: SnowinRio
        networks:
            - minionet
        restart: unless-stopped


volumes:
  minio-data:
    driver: local

networks:
  minionet:
    driver: bridge